server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/usuariosbd
    username: root
    password: carlosserna12

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
appDescription: "USUARIOS"
appVersion: "1.0.0"

